#! /bin/bash

while :
do
echo -e "  \e[1;32mDo you want to generate a new bin? \e[0m"
echo ""
echo -n -e "  \e[1;32m(\e[0m\e[1;37myes\e[0m\e[1;32m)  (\e[0m\e[1;37mno\e[0m\e[1;32m) :\e[0m"
read bin
case $bin in
yes)
#! /bash/bin
bash generador.sh
exit
;;
no)
#! /bash/bin
exit
;;
esac
done
